name: Build AppRetro

on:
  
  workflow_dispatch:

jobs:
  build:
    name: Build IPA with Theos
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid dpkg make

      - name: Setup Theos & SDKs
        run: |
          echo "Cloning Theos..."
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          echo "Cloning iOS SDKs..."
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build and Package
        run: |
          # 1. 编译并生成 Theos 的 Staging 目录 (会在根目录生成 '_' 文件夹)
          make package FINALPACKAGE=1
          
          # 2. 手动构建 IPA (完美绕过 Theos FORMAT=ipa 的 Bug)
          echo "手动打包 IPA..."
          mkdir -p Payload
          
          # 复制已签名并处理好的 .app 到 Payload 目录
          cp -r _/Applications/AppRetro.app Payload/
          
          # 压缩为标准的 IPA 文件
          zip -r9 AppRetro.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppRetro-Release
          path: AppRetro.ipa # 指向刚才手动生成的 IPA
          if-no-files-found: error
