name: Build AppRetro

on:
 
  workflow_dispatch:

jobs:
  build:
    name: Build IPA with Theos
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install ldid dpkg make

      - name: Setup Theos & SDKs
        run: |
          echo "Cloning Theos..."
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          echo "Cloning iOS SDKs..."
          # 【核心修复】：强行删除 Theos 自带的空 sdks 文件夹，为克隆腾出位置
          rm -rf $THEOS/sdks
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build and Package
        run: |
          # 编译并生成 .app
          make package FINALPACKAGE=1
          
          # 手动构建 IPA
          echo "手动打包 IPA..."
          mkdir -p Payload
          cp -r _/Applications/AppRetro.app Payload/
          zip -r9 AppRetro.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppRetro-Release
          path: AppRetro.ipa
          if-no-files-found: error
